version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - cd api/
      - npm install
      - cd ..
      - npm install
    finally:
      - echo This always runs even if the update or install command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build
    finally:
      - echo This always runs even if the build command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`.
      - zip -r zap-spotify.zip build/ api/

reports: 
  CypressReports:
    files: 
      - 'cypress/*'
      - 'test-results.xml'

artifacts:
  files:
    - zap-spotify.zip
    - appspec.yml
    - deployment.sh
    